import type { MenuItem, Settings } from '@/types';

export const SEED_MENU: MenuItem[] = [
  {
    id: 's1',
    name: 'Classic Bruschetta',
    description: 'Toasted ciabatta, vine tomatoes, fresh basil, garlic olive oil.',
    price: 7.5,
    category: 'Starters',
    image: 'https://images.pexels.com/photos/2532006/pexels-photo-2532006.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    available: true,
  },
  {
    id: 's2',
    name: 'Caesar Salad',
    description: 'Crisp romaine, croutons, parmesan, anchovy dressing.',
    price: 8.0,
    category: 'Starters',
    image: 'https://images.pexels.com/photos/19938473/pexels-photo-19938473.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    available: true,
  },
  {
    id: 'm1',
    name: 'Signature Cheeseburger',
    description: 'Beef patty, aged cheddar, house sauce, brioche bun, fries.',
    price: 14.0,
    category: 'Mains',
    image: 'https://images.pexels.com/photos/17095325/pexels-photo-17095325.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    available: true,
  },
  {
    id: 'm2',
    name: 'Spaghetti Carbonara',
    description: 'Pancetta, egg yolk, pecorino, cracked pepper.',
    price: 13.5,
    category: 'Mains',
    image: 'https://images.pexels.com/photos/546945/pexels-photo-546945.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    available: true,
  },
  {
    id: 'm3',
    name: 'Grilled Ribeye Steak',
    description: '8oz ribeye, roasted tomato, pepper, chimichurri.',
    price: 22.0,
    category: 'Mains',
    image: 'https://images.pexels.com/photos/28292008/pexels-photo-28292008.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    available: true,
  },
  {
    id: 'd1',
    name: 'Mint Mojito',
    description: 'White rum, mint, lime, soda. Refreshing and bright.',
    price: 9.0,
    category: 'Drinks',
    image: 'https://images.pexels.com/photos/7985176/pexels-photo-7985176.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    available: true,
  },
  {
    id: 'd2',
    name: 'Iced Caramel Latte',
    description: 'Double espresso, caramel, cold milk over ice.',
    price: 5.5,
    category: 'Drinks',
    image: 'https://images.pexels.com/photos/35229818/pexels-photo-35229818.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    available: true,
  },
  {
    id: 'ds1',
    name: 'Chocolate Lava Cake',
    description: 'Warm molten center, vanilla bean ice cream.',
    price: 7.0,
    category: 'Desserts',
    image: 'https://images.pexels.com/photos/10249461/pexels-photo-10249461.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    available: true,
  },
];

export const DEFAULT_SETTINGS: Settings = {
  restaurantName: 'Bella Cucina',
  masterPin: '1234',
  taxRate: 8,
  currency: '$',
  lanUrl: '',
  tableCount: 12,
  soundEnabled: true,
};
